services:
  # service for fastapi backend 
  backend:
    build:
      context: '.'
      dockerfile: 'Dockerfile.back'
    container_name: 'npi_backend'
    volumes:
      - './app/backend:/app'
    environment:
      - 'DATABASE_URL=mysql://npi:npi@database/ayomi?charset=utf8mb4'
    ports:
      - '8000:8080'
    networks:
      - npi_network
    depends_on:
      - database

  # service for react frontend
  frontend:
    build:
      context: '.'
      dockerfile: 'Dockerfile.front'
    container_name: 'npi_frontend'
    working_dir: '/app'
    ports:
      - '3000:3000'
    networks:
      - npi_network

  # service for mysql database
  database:
    image: 'mysql:5.7'
    container_name: 'npi_database'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ayomi"
      MYSQL_USER: "npi"
      MYSQL_PASSWORD: "npi"
    networks:
      - npi_network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  npi_network:
    driver: bridge