FROM node:23.1.0-alpine3.19

WORKDIR /app

COPY ./app/frontend/package.json package.json
COPY ./app/frontend/package-lock.json package-lock.json

RUN npm install

CMD ["npm", "install"]

COPY ./app/frontend /app

CMD ["npm", "run", "dev"]